version: "2"
services:
  django:
    container_name: django_server_01
    build:
      context: .
      dockerfile: Dockerfile
    image: docker_tutorial_django
    stdin_open: true
    tty: true
    volumes: 
      - .:/var/www/myproject
    ports:
      - "8000:8000"
