# Generated by Django 3.0.6 on 2020-05-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('an', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pn', models.CharField(db_index=True, max_length=32)),
                ('auth', models.CharField(db_index=True, max_length=16)),
                ('mode', models.CharField(choices=[('RG', 'registering'), ('AV', 'available'), ('BK', 'booked'), ('OF', 'offline'), ('LK', 'locked')], db_index=True, default='OF', max_length=2)),
                ('pid', models.IntegerField(db_index=True, null=True)),
                ('tid', models.IntegerField(db_index=True, default=-1)),
                ('dl', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(db_index=True, max_length=64, null=True)),
                ('gdr', models.CharField(db_index=True, max_length=16, null=True)),
                ('age', models.IntegerField(db_index=True, null=True)),
                ('hs', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'driver',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('an', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('kind', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'location',
                'ordering': ['lat', 'lng'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(db_index=True, max_length=64, unique=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('alt', models.IntegerField()),
                ('wt', models.IntegerField()),
            ],
            options={
                'db_table': 'place',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('pct', models.IntegerField(db_index=True)),
            ],
            options={
                'db_table': 'progress',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('idy', models.IntegerField()),
                ('dist', models.IntegerField()),
            ],
            options={
                'db_table': 'route',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st', models.CharField(choices=[('RQ', 'requested'), ('AS', 'assigned'), ('ST', 'started'), ('TR', 'terminated'), ('FN', 'finished'), ('PD', 'paid'), ('CN', 'cancelled'), ('DN', 'denied'), ('TO', 'timeout'), ('FL', 'failed')], db_index=True, default='RQ', max_length=2)),
                ('uan', models.BigIntegerField(db_index=True)),
                ('dan', models.BigIntegerField(db_index=True, default=0)),
                ('van', models.BigIntegerField(db_index=True, default=0)),
                ('rtime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atime', models.DateTimeField(db_index=True, null=True)),
                ('stime', models.DateTimeField(db_index=True, null=True)),
                ('etime', models.DateTimeField(db_index=True, null=True)),
                ('srcid', models.IntegerField(db_index=True)),
                ('dstid', models.IntegerField(db_index=True)),
                ('npas', models.IntegerField()),
                ('rtype', models.CharField(choices=[('RIDE', 0), ('RENT', 1)], db_index=True, default=2, max_length=10)),
                ('pmode', models.CharField(choices=[('CASH', 0), ('UPI', 1)], db_index=True, default=1, max_length=10)),
            ],
            options={
                'db_table': 'trip',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('an', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pn', models.CharField(db_index=True, max_length=32)),
                ('auth', models.CharField(db_index=True, max_length=16)),
                ('pid', models.IntegerField(db_index=True, null=True)),
                ('tid', models.IntegerField(db_index=True, default=-1)),
                ('name', models.CharField(db_index=True, max_length=64, null=True)),
                ('gdr', models.CharField(db_index=True, max_length=16, null=True)),
                ('age', models.SmallIntegerField(db_index=True, null=True)),
                ('dl', models.CharField(max_length=20, null=True)),
                ('hs', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('an', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tid', models.BigIntegerField(db_index=True, default=-1)),
                ('regn', models.CharField(db_index=True, max_length=16)),
                ('dist', models.IntegerField(null=True)),
                ('hrs', models.FloatField(null=True)),
                ('pid', models.IntegerField(db_index=True, null=True)),
                ('vtype', models.IntegerField(default=3, null=True)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['idx', 'idy'], name='route_idx_f49387_idx'),
        ),
    ]
