# Generated by Django 3.0.6 on 2020-06-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='hrs',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
