# Generated by Django 3.0.6 on 2020-06-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0002_trip_hrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('an', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pn', models.CharField(db_index=True, max_length=32)),
                ('auth', models.CharField(db_index=True, max_length=16)),
                ('pid', models.IntegerField(db_index=True, null=True)),
                ('tid', models.IntegerField(db_index=True, default=-1)),
                ('dl', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(db_index=True, max_length=64, null=True)),
                ('gdr', models.CharField(db_index=True, max_length=16, null=True)),
                ('age', models.IntegerField(db_index=True, null=True)),
                ('hs', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'super',
                'managed': True,
            },
        ),
    ]
