# Generated by Django 3.0.6 on 2020-06-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0003_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='tid',
        ),
    ]
