# Generated by Django 3.0.6 on 2020-07-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0004_remove_supervisor_tid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('an', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pn', models.CharField(db_index=True, max_length=32)),
                ('auth', models.CharField(db_index=True, max_length=16)),
                ('mode', models.CharField(choices=[('RG', 'registering'), ('AV', 'available'), ('BK', 'booked'), ('OF', 'offline'), ('LK', 'locked')], db_index=True, default='OF', max_length=2)),
                ('pid', models.IntegerField(db_index=True, null=True)),
                ('tid', models.IntegerField(db_index=True, default=-1)),
                ('dl', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(db_index=True, max_length=64, null=True)),
                ('gdr', models.CharField(db_index=True, max_length=16, null=True)),
                ('age', models.IntegerField(db_index=True, null=True)),
                ('hs', models.CharField(max_length=50, null=True)),
                ('veh', models.CharField(choices=[('0', 'false'), ('1', 'true')], db_index=True, default='0', max_length=1)),
            ],
            options={
                'db_table': 'agent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st', models.CharField(choices=[('RQ', 'requested'), ('AS', 'assigned'), ('ST', 'started'), ('FN', 'finished'), ('PD', 'paid'), ('CN', 'cancelled'), ('DN', 'denied'), ('TO', 'timeout'), ('FL', 'failed')], db_index=True, default='RQ', max_length=2)),
                ('uan', models.BigIntegerField(db_index=True)),
                ('dan', models.BigIntegerField(db_index=True, default=0)),
                ('van', models.BigIntegerField(db_index=True, default=0)),
                ('rtime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atime', models.DateTimeField(db_index=True, null=True)),
                ('stime', models.DateTimeField(db_index=True, null=True)),
                ('etime', models.DateTimeField(db_index=True, null=True)),
                ('srcpin', models.IntegerField(db_index=True)),
                ('dstpin', models.IntegerField(db_index=True)),
                ('itype', models.CharField(choices=[('DOC', 0), ('CLO', 1), ('FOOD', 2), ('HOUSE', 3), ('ELECT', 4), ('OTHER', 5)], db_index=True, default='OTHER', max_length=6)),
                ('idim', models.CharField(choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE'), ('XL', 'EXTRALARGE'), ('XXL', 'EXTRAALARGE')], db_index=True, default='M', max_length=6)),
                ('pmode', models.CharField(choices=[('CASH', 0), ('UPI', 1)], db_index=True, default=1, max_length=10)),
            ],
            options={
                'db_table': 'delivery',
                'managed': True,
            },
        ),
    ]
