# Generated by Django 3.0.6 on 2020-07-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0005_agent_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='dstlat',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='dstlng',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='srclat',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='srclng',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
