# Generated by Django 3.0.6 on 2020-07-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0006_auto_20200702_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='did',
            field=models.IntegerField(db_index=True, default=-1),
        ),
    ]
