# Generated by Django 3.0.6 on 2020-07-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0008_auto_20200706_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='dstadd',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='dstland',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='dstphone',
            field=models.CharField(db_index=True, default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='delivery',
            name='srcadd',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='srcland',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='delivery',
            name='srcphone',
            field=models.CharField(db_index=True, default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='itype',
            field=models.CharField(choices=[('DOC', 0), ('CLO', 1), ('FOO', 2), ('HOU', 3), ('ELE', 4), ('OTH', 5)], db_index=True, default='OTHER', max_length=6),
        ),
    ]
