# Generated by Django 3.0.6 on 2020-07-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0009_auto_20200710_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='dstper',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='srcper',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dstadd',
            field=models.CharField(default='_dadd', max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dstland',
            field=models.CharField(default='_dland', max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='srcadd',
            field=models.CharField(default='_sadd', max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='srcland',
            field=models.CharField(default='_sland', max_length=200),
        ),
    ]
