# Generated by Django 3.0.6 on 2020-07-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0010_auto_20200710_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='dstlat',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='dstlng',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='srclat',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='srclng',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
