# Generated by Django 3.0.6 on 2020-07-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0011_auto_20200711_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='dstlat',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dstlng',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='srclat',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='srclng',
            field=models.FloatField(db_index=True),
        ),
    ]
