# Generated by Django 3.0.6 on 2020-07-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0012_auto_20200711_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='van',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
