# Generated by Django 3.0.6 on 2020-07-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0013_driver_van'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='dan',
            field=models.BigIntegerField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='driver',
            name='van',
            field=models.BigIntegerField(db_index=True, default=-1),
        ),
    ]
