# Generated by Django 3.0.6 on 2020-07-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0014_auto_20200712_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='adddet',
            field=models.CharField(default='_adddet', max_length=150),
        ),
        migrations.AddField(
            model_name='delivery',
            name='check',
            field=models.CharField(choices=[('NO', 'NONE'), ('FR', 'FRAGILE'), ('FL', 'FLAMMABLE'), ('LI', 'LIQUID'), ('KD', 'KEEPDRY'), ('KW', 'KEEPWARM'), ('KW', 'KEEPCOLD')], db_index=True, default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dstland',
            field=models.CharField(db_index=True, default='_dland', max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='srcland',
            field=models.CharField(db_index=True, default='_sland', max_length=200),
        ),
    ]
