# Generated by Django 3.0.6 on 2020-07-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0015_auto_20200713_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='adddet',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='check',
        ),
        migrations.AddField(
            model_name='delivery',
            name='details',
            field=models.CharField(default='_', max_length=150),
        ),
        migrations.AddField(
            model_name='delivery',
            name='fl',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='fr',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='kc',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='kd',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='kw',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='li',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='tip',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dstadd',
            field=models.CharField(default='_', max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dstland',
            field=models.CharField(db_index=True, default='_', max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dstphone',
            field=models.CharField(db_index=True, default='_', max_length=15),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='itype',
            field=models.CharField(choices=[('DOC', 0), ('CLO', 1), ('FOO', 2), ('HOU', 3), ('ELE', 4), ('OTH', 5)], db_index=True, default='OTH', max_length=6),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='srcadd',
            field=models.CharField(default='_', max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='srcland',
            field=models.CharField(db_index=True, default='_', max_length=200),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='srcphone',
            field=models.CharField(db_index=True, default='_', max_length=15),
        ),
    ]
