# Generated by Django 3.0.6 on 2020-07-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0016_auto_20200713_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='details',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dstadd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dstland',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dstphone',
            field=models.CharField(db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='srcadd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='srcland',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='srcphone',
            field=models.CharField(db_index=True, max_length=15, null=True),
        ),
    ]
