# Generated by Django 3.0.6 on 2020-07-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0017_auto_20200713_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='dstid',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dstlat',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dstlng',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='npas',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='rtype',
            field=models.CharField(choices=[('0', 0), ('1', 1)], db_index=True, default=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='srcid',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='srclat',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='srclng',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
