# Generated by Django 3.0.6 on 2020-07-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0018_auto_20200716_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='dan',
            field=models.BigIntegerField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='van',
            field=models.BigIntegerField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dan',
            field=models.BigIntegerField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dstid',
            field=models.IntegerField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dstlat',
            field=models.FloatField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dstlng',
            field=models.FloatField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='srcid',
            field=models.IntegerField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='srclat',
            field=models.FloatField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='srclng',
            field=models.FloatField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='trip',
            name='van',
            field=models.BigIntegerField(db_index=True, default=-1),
        ),
    ]
