# Generated by Django 3.0.6 on 2020-07-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0019_auto_20200717_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='mark',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='driver',
            name='mark',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='mark',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dstid',
            field=models.IntegerField(db_index=True, default=2),
        ),
        migrations.AlterField(
            model_name='trip',
            name='srcid',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='hs',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
