# Generated by Django 3.0.6 on 2020-07-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0020_auto_20200718_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='mark',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
