# Generated by Django 3.0.6 on 2020-07-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0021_vehicle_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='rvtype',
            field=models.IntegerField(default=3, null=True),
        ),
    ]
