# Generated by Django 3.0.6 on 2020-07-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0022_trip_rvtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RIDE', 'ride'), ('RENT', 'rental'), ('DELI', 'delivery'), ('NAN', 'null')], db_index=True, default='NAN', max_length=4)),
                ('rating', models.CharField(choices=[('AT', 'attitude'), ('VC', 'vehiclecon'), ('CL', 'cleanliness'), ('OT', 'other')], db_index=True, default='OT', max_length=20)),
                ('money', models.FloatField(db_index=True, default=0.0)),
            ],
            options={
                'db_table': 'rate',
                'managed': True,
            },
        ),
    ]
