# Generated by Django 3.0.6 on 2020-07-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0023_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='fl',
            new_name='br',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='kd',
            new_name='pe',
        ),
        migrations.AddField(
            model_name='delivery',
            name='express',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='itype',
            field=models.CharField(choices=[('DOC', 0), ('CLO', 1), ('FOO', 2), ('HOU', 3), ('ELE', 4), ('OTH', 5)], db_index=True, default='OTH', max_length=20),
        ),
    ]
