# Generated by Django 3.0.6 on 2020-07-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0025_auto_20200729_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='scid',
            field=models.IntegerField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='st',
            field=models.CharField(choices=[('SC', 'scheduled'), ('PD', 'paid'), ('RC', 'reached'), ('RQ', 'requested'), ('AS', 'assigned'), ('ST', 'started'), ('FN', 'finished'), ('CN', 'cancelled'), ('DN', 'denied'), ('TO', 'timeout'), ('FL', 'failed')], db_index=True, default='SC', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='did',
            field=models.CharField(db_index=True, default='', max_length=11),
        ),
    ]
