# Generated by Django 3.0.6 on 2020-07-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0026_auto_20200729_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='scid',
            field=models.CharField(db_index=True, default='', max_length=11),
        ),
    ]
