# Generated by Django 3.0.6 on 2020-07-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0027_auto_20200729_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rev',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.CharField(choices=[('attitude', 'attitude'), ('vehiclecon', 'vehiclecondition'), ('cleanliness', 'cleanliness'), ('other', ' other ')], db_index=True, default='OT', max_length=20),
        ),
    ]
