# Generated by Django 3.0.6 on 2020-08-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zp', '0028_auto_20200730_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adhar',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
